/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_exchange_jni_MatchingEngineJNI */

#ifndef _Included_com_example_exchange_jni_MatchingEngineJNI
#define _Included_com_example_exchange_jni_MatchingEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_exchange_jni_MatchingEngineJNI
 * Method:    initializeEngine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_initializeEngine
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_exchange_jni_MatchingEngineJNI
 * Method:    addOrder
 * Signature: (Ljava/lang/String;JIZ)V
 */
JNIEXPORT void JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_addOrder
  (JNIEnv *, jobject, jstring, jlong, jint, jboolean);

/*
 * Class:     com_example_exchange_jni_MatchingEngineJNI
 * Method:    matchOrders
 * Signature: ()[Lcom/example/exchange/jni/MatchingEngineJNI/Trade;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_matchOrders
  (JNIEnv *, jobject);

/*
 * Class:     com_example_exchange_jni_MatchingEngineJNI
 * Method:    getOrderBookSummary
 * Signature: ()Lcom/example/exchange/jni/MatchingEngineJNI/OrderBookSummary;
 */
JNIEXPORT jobject JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_getOrderBookSummary
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
