/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_exchange_jni_MatchingEngineJNI */
using namespace std;

#ifndef _Included_com_example_exchange_jni_MatchingEngineJNI
#define _Included_com_example_exchange_jni_MatchingEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_exchange_jni_MatchingEngineJNI
 * Method:    printHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_exchange_jni_MatchingEngineJNI_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
